version: '3'

networks:
    backend:
        driver: ${NETWORKS_DRIVER}

volumes:
    mysql:
        driver: ${VOLUMES_DRIVER}
    phpmyadmin:
        driver: ${VOLUMES_DRIVER}

services:
    workspace:
        build:
            context: ./workspace
        volumes:
            - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
        extra_hosts:
            - "dockerhost:${DOCKER_HOST_IP}"
        ports:
            - "${WORKSPACE_PORT}:3000"
            - "${WORKSPACE_SSH_PORT}:22"
        tty: true
        networks:
            - backend

    mysql:
        build:
            context: ./mysql
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - TZ=${WORKSPACE_TIMEZONE}
        volumes:
            - ${DATA_PATH_HOST}/mysql:/var/lib/mysql
        ports:
            - "${MYSQL_PORT}:3306"
        networks:
            - backend

    phpmyadmin:
        build: ./phpmyadmin
        environment:
            - PMA_ARBITRARY=1
            - MYSQL_USER=${PMA_USER}
            - MYSQL_PASSWORD=${PMA_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${PMA_ROOT_PASSWORD}
        ports:
            - "${PMA_PORT}:80"
        depends_on:
            - "${PMA_DB_ENGINE}"
        networks:
            - backend
